apiVersion: v2
name: app-chart
description: A Helm Chart for generating Kubernetes resources for app deployment
type: application
version: 1.0.0

maintainers:
  - name: komailo
    url: https://github.com/komailo/helm-charts
sources:
  - https://github.com/komailo/helm-charts

dependencies:
  - name: external-secrets-manager
    version: "1.2.0"
    repository: https://komailo.github.io/helm-charts
    condition: external-secrets-manager.enabled
    alias: esm
  - name: mariadb
    version: "25.0.1"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mariadb.enabled
  - name: library-app-chart
    version: ">=0.0.0"
    repository: file://../library-app-chart
