{{- range $jobName, $job := .Values.cronJobs }}
{{- if or (not (hasKey $job "enabled")) $job.enabled }}
{{- $metadataLabels := merge (dict "app" $jobName) (default (dict) $job.labels) }}
{{- $jobTemplate := default (dict) $job.jobTemplate }}
{{- $pod := default (dict) $job.pod }}
{{- $podLabels := merge (dict "app" $jobName) (default (dict) $pod.labels) }}
{{- $container := required (printf "cronJobs.%s.container is required" $jobName) $job.container }}
{{- $imageConfig := required (printf "cronJobs.%s.container.image is required" $jobName) $container.image }}
{{- $imageRepo := required (printf "cronJobs.%s.container.image.repository is required" $jobName) $imageConfig.repository }}
{{- $imageTag := default "latest" $imageConfig.tag }}
{{- $imagePullPolicy := default "IfNotPresent" $imageConfig.pullPolicy }}
{{- $volumes := $job.volumes }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $jobName }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ toYaml $metadataLabels | nindent 4 }}
{{- with $job.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
{{- end }}
spec:
  schedule: {{ required (printf "cronJobs.%s.schedule is required" $jobName) $job.schedule | quote }}
  concurrencyPolicy: {{ default "Allow" $job.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ default 3 $job.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ default 1 $job.failedJobsHistoryLimit }}
{{- with $job.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ . }}
{{- end }}
{{- if hasKey $job "suspend" }}
  suspend: {{ $job.suspend }}
{{- end }}
  jobTemplate:
    spec:
{{- with $jobTemplate.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ . }}
{{- end }}
{{- with $jobTemplate.backoffLimit }}
      backoffLimit: {{ . }}
{{- end }}
{{- with $jobTemplate.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ . }}
{{- end }}
{{- with $jobTemplate.parallelism }}
      parallelism: {{ . }}
{{- end }}
{{- with $jobTemplate.completions }}
      completions: {{ . }}
{{- end }}
      template:
        metadata:
          labels:
{{ toYaml $podLabels | nindent 12 }}
{{- with $pod.annotations }}
          annotations:
{{ toYaml . | nindent 12 }}
{{- end }}
        spec:
          restartPolicy: {{ default "OnFailure" $pod.restartPolicy }}
{{- with $pod.serviceAccountName }}
          serviceAccountName: {{ . }}
{{- end }}
{{- with $pod.nodeSelector }}
          nodeSelector:
{{ toYaml . | nindent 12 }}
{{- end }}
{{- with $pod.imagePullSecrets }}
          imagePullSecrets:
{{ toYaml . | nindent 12 }}
{{- end }}
{{- with $pod.tolerations }}
          tolerations:
{{ toYaml . | nindent 12 }}
{{- end }}
{{- with $pod.affinity }}
          affinity:
{{ toYaml . | nindent 12 }}
{{- end }}
{{- with $pod.securityContext }}
          securityContext:
{{ toYaml . | nindent 12 }}
{{- end }}
          containers:
            - name: {{ default $jobName $container.name }}
              image: "{{ $imageRepo }}:{{ $imageTag }}"
              imagePullPolicy: {{ $imagePullPolicy }}
{{- with $container.command }}
              command:
{{ toYaml . | nindent 16 }}
{{- end }}
{{- with $container.args }}
              args:
{{ toYaml . | nindent 16 }}
{{- end }}
{{- with (include "app-chart.deployment.envFrom" (dict "envFrom" $container.envFrom)) }}{{ . | nindent 14 }}{{- end }}
{{- with (include "app-chart.deployment.env" (dict "env" $container.env "context" $ "appName" $jobName)) }}{{ . | nindent 14 }}{{- end }}
{{- with (include "app-chart.deployment.volumeMounts" (dict "volumes" $volumes)) }}{{ . | nindent 14 }}{{- end }}
{{- with $container.securityContext }}
              securityContext:
{{ toYaml . | nindent 16 }}
{{- end }}
{{- with $container.resources }}
              resources:
{{ toYaml . | nindent 16 }}
{{- end }}
{{- with (include "app-chart.deployment.volumes" (dict "volumes" $volumes)) }}{{ . | nindent 10 }}{{- end }}
{{- end }}
{{- end }}
