{{- range $appName, $app := .Values.apps }}
{{- if or (not (hasKey $app "enabled")) $app.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}
  namespace: {{ $.Release.Namespace }}
spec:
  {{- if $app.deployStrategy }}
  strategy:
    type: {{ $app.deployStrategy }}
  {{- end }}
  replicas: {{ $app.replicas | default 1 }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ $appName }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
    spec:
      {{- if $app.initContainers }}
      initContainers:
{{- range $init := $app.initContainers }}
{{- include "app-chart.deployment.container" (dict "container" $init "name" $init.name "appName" $appName "context" $) | nindent 8 }}
{{- end }}
      {{- end }}
      containers:
{{- include "app-chart.deployment.container" (dict "container" $app "name" $appName "appName" $appName "context" $) | nindent 8 }}
{{- if $app.sidecars }}
{{- range $sidecar := $app.sidecars }}
{{- include "app-chart.deployment.container" (dict "container" $sidecar "name" $sidecar.name "appName" $appName "context" $) | nindent 8 }}
{{- end }}
{{- end }}
    {{- with (include "app-chart.deployment.volumes" (dict "volumes" $app.volumes "configMounts" $app.configMounts "configMaps" $.Values.configMaps "appName" $appName)) }}{{ . | nindent 6 }}{{- end }}

{{- end }}
{{- end }}
