{{- $collectedJson := include "app-chart.imagePullSecrets.collectExternalSecrets" . -}}
{{- $collected := fromJson $collectedJson -}}
{{- range $secretName, $secret := $collected }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $secretName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "app-chart.labels" (dict "appName" $secretName "context" $) | nindent 4 }}
    {{- with $secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ default $.Values.globals.refreshInterval $secret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ default $.Values.globals.secretStoreRefName $secret.secretStoreRefName | quote }}
    kind: {{ default $.Values.globals.secretStoreRefKind $secret.secretStoreRefKind | quote }}
  target:
    name: {{ default $secretName $secret.targetName }}
    creationPolicy: {{ default "Owner" $secret.creationPolicy }}
    template:
      type: {{ default "kubernetes.io/dockerconfigjson" $secret.type }}
  data:
    - secretKey: {{ default ".dockerconfigjson" $secret.secretKey }}
      remoteRef:
        key: {{ $secret.remoteRefKey | quote }}
        {{- with $secret.property }}
        property: {{ . | quote }}
        {{- end }}
        {{- with $secret.version }}
        version: {{ . | quote }}
        {{- end }}
{{- end }}
