{{- $backupTracker := dict "enabled" false }}
{{- $defaults := default (dict) .Values.defaults }}
{{- $defaultBackup := default (dict) $defaults.backup }}
{{- $defaultPruning := default (dict) $defaultBackup.pruningPolicy }}
{{- $defaultSchedule := default "@hourly" $defaultBackup.schedule }}
{{- $defaultForgetSchedule := default "@daily" $defaultBackup.forgetSchedule }}
{{- range $pvcName, $pvc := .Values.persistentVolumeClaims }}
{{- if and $pvc.backup $pvc.backup.enabled }}
{{- $pruning := default (dict) $pvc.backup.pruningPolicy }}
{{- $keepLast := default $defaultPruning.keepLast $pruning.keepLast }}
{{- $keepHourly := default $defaultPruning.keepHourly $pruning.keepHourly }}
{{- $keepDaily := default $defaultPruning.keepDaily $pruning.keepDaily }}
{{- $keepWeekly := default $defaultPruning.keepWeekly $pruning.keepWeekly }}
{{- $keepMonthly := default $defaultPruning.keepMonthly $pruning.keepMonthly }}
{{- $keepYearly := default $defaultPruning.keepYearly $pruning.keepYearly }}
{{- $forgetSchedule := default $defaultForgetSchedule $pvc.backup.forgetSchedule }}
{{- $_ := set $backupTracker "enabled" true }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: restic-backup-{{ $pvcName }}
  namespace: {{ $.Release.Namespace }}
data:
  RETRY_LOCK: "15m"
  HOSTNAME: "{{ $.Release.Namespace }}-{{ $pvcName }}"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: restic-backup-{{ $pvcName }}
  namespace: {{ $.Release.Namespace }}
spec:
  schedule: "{{ default $defaultSchedule $pvc.backup.schedule }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 172800 # 2 days
      backoffLimit: 4
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: restic
              image: {{ printf "%s:%s" $.Values.restic.image.repository $.Values.restic.image.tag }}
              envFrom:
                - secretRef:
                    name: restic-backup
                  prefix: "RESTIC_"
                - configMapRef:
                    name: restic-backup-{{ $pvcName }}
                  prefix: "RESTIC_"
              volumeMounts:
                - name: data
                  mountPath: /data
                - name: restic-cache
                  mountPath: /cache/restic
              command:
                - /bin/sh
                - -c
                - |
                  set -euo pipefail

                  cd /data

                  # Random jitter between 0 and 300 seconds (0-5 minutes)
                  JITTER=$((RANDOM % 300))
                  echo "Sleeping for ${JITTER}s before starting work..."
                  sleep "${JITTER}"

                  export RESTIC_PASSWORD=${RESTIC_password}
                  export RESTIC_REPOSITORY=${RESTIC_repository}
                  export AWS_ACCESS_KEY_ID=${RESTIC_aws_access_key_id}
                  export AWS_SECRET_ACCESS_KEY=${RESTIC_aws_secret_access_key}
                  export AWS_DEFAULT_REGION=${RESTIC_aws_default_region}

                  export RESTIC_CACHE_DIR=/cache/restic

                  echo "[backup] Running backup of /data ..."
                  restic backup . \
                    --skip-if-unchanged \
                    --exclude-if-present NO_BACKUP.TAG \
                    --retry-lock "$RESTIC_RETRY_LOCK" \
                    --host "$RESTIC_HOSTNAME" \
                    --tag="pvc={{ $pvcName }}" \
                    --tag="namespace={{ $.Release.Namespace }}"

                  echo "[backup] Done."

          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: {{ $pvcName }}
            - name: restic-cache
              persistentVolumeClaim:
                claimName: {{ printf "%s-restic-cache" $pvcName }}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: restic-backup-{{ $pvcName }}-forget
  namespace: {{ $.Release.Namespace }}
spec:
  schedule: "{{ $forgetSchedule }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 172800 # 2 days
      backoffLimit: 4
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: restic
              image: {{ printf "%s:%s" $.Values.restic.image.repository $.Values.restic.image.tag }}
              envFrom:
                - secretRef:
                    name: restic-backup
                  prefix: "RESTIC_"
                - configMapRef:
                    name: restic-backup-{{ $pvcName }}
                  prefix: "RESTIC_"
              volumeMounts:
                - name: restic-cache
                  mountPath: /cache/restic
              command:
                - /bin/sh
                - -c
                - |
                  set -euo pipefail

                  export RESTIC_PASSWORD=${RESTIC_password}
                  export RESTIC_REPOSITORY=${RESTIC_repository}
                  export AWS_ACCESS_KEY_ID=${RESTIC_aws_access_key_id}
                  export AWS_SECRET_ACCESS_KEY=${RESTIC_aws_secret_access_key}
                  export AWS_DEFAULT_REGION=${RESTIC_aws_default_region}

                  export RESTIC_CACHE_DIR=/cache/restic

                  echo "[restic unlock] Starting stale lock removal operation"
                  restic unlock

                  echo "[retention] Applying retention policy..."
                  restic forget \
                    --keep-last "{{ $keepLast }}" \
                    --keep-hourly "{{ $keepHourly }}" \
                    --keep-daily "{{ $keepDaily }}" \
                    --keep-weekly "{{ $keepWeekly }}" \
                    --keep-monthly "{{ $keepMonthly }}" \
                    --keep-yearly "{{ $keepYearly }}" \
                    --retry-lock "$RESTIC_RETRY_LOCK" \
                    --tag="pvc={{ $pvcName }}" \
                    --tag="namespace={{ $.Release.Namespace }}"

                  echo "[retention] Done."

          volumes:
            - name: restic-cache
              persistentVolumeClaim:
                claimName: {{ printf "%s-restic-cache" $pvcName }}

{{- end }}
{{- end }}

{{- if $backupTracker.enabled }}
{{- /* Expose only the External Secrets inputs we need for restic backups */}}
{{- $clusterName := default $.Release.Namespace $.Values.clusterName }}
{{- $subPathSecret := dict "name" "restic-backup" "remoteRefKey" (printf "/k8s-%s/restic-backup" $clusterName) }}
{{- $externalValues := deepCopy .Values }}
{{- $_ := set $externalValues "SubPathSecrets" (list $subPathSecret) }}
{{- include "external-secret-manager.subpath" (dict "Values" $externalValues "Release" .Release "Chart" .Chart "Capabilities" .Capabilities) -}}
{{- end }}

{{- range $pvcName, $pvc := .Values.persistentVolumeClaims }}
{{- if and $pvc.backup $pvc.backup.enabled }}
{{ include "library-app-chart.pvc.claim" (dict "name" (printf "%s-restic-cache" $pvcName) "pvc" $pvc "root" $) }}
{{- end }}
{{- end }}
