{{- range $appName, $app := .Values.apps }}
{{- if and (or (not (hasKey $app "enabled")) $app.enabled) (and $app.vpa $app.vpa.enabled) }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ $appName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "app-chart.labels" (dict "appName" $appName "context" $) | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ $appName }}
  updatePolicy:
    updateMode: {{ $app.vpa.updateMode | default "Off" | quote }}
  {{- if or $app.vpa.minAllowed $app.vpa.maxAllowed }}
  resourcePolicy:
    containerPolicies:
      - containerName: {{ $appName }}
        {{- if $app.vpa.minAllowed }}
        minAllowed:
          {{- toYaml $app.vpa.minAllowed | nindent 10 }}
        {{- end }}
        {{- if $app.vpa.maxAllowed }}
        maxAllowed:
          {{- toYaml $app.vpa.maxAllowed | nindent 10 }}
        {{- end }}
  {{- end }}
{{- end }}
{{- end }}
