{{- if .Values.resticBackup.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: restic-backup
  namespace: "{{ .Release.Namespace }}"
data:
  RETRY_LOCK: "15m"
  HOSTNAME: "{{ .Release.Namespace }}"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: restic-backup
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "@daily"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 172800 # 2 days
      backoffLimit: 4
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: restic
              image: restic/restic:latest
              envFrom:
                - secretRef:
                    name: restic-backup
                  prefix: "RESTIC_"
                - configMapRef:
                    name: restic-backup
                  prefix: "RESTIC_"
              volumeMounts:
                - name: restic-cache
                  mountPath: /cache/restic
              command:
                - /bin/sh
                - -c
                - |
                  set -euo pipefail

                  export B2_ACCOUNT_ID=${RESTIC_b2_account_id}
                  export B2_ACCOUNT_KEY=${RESTIC_b2_account_key}
                  export RESTIC_PASSWORD=${RESTIC_password}
                  export RESTIC_REPOSITORY=${RESTIC_repository}
                  export RESTIC_CACHE_DIR=/cache/restic

                  echo "[backup prune] Starting prune operation"
                  restic prune

                  restic prune --help

                  echo "[backup check] Starting check operation"

                  restic check

                  restic check --help

          volumes:
            - name: restic-cache
              persistentVolumeClaim:
                claimName: "{{ .Values.resticBackup.cachePVC.name }}"

{{- /* Expose only the External Secrets inputs we need for restic backups */}}
{{- $clusterName := default .Release.Namespace .Values.clusterName }}
{{- $subPathSecret := dict "name" "restic-backup" "remoteRefKey" (printf "/k8s-%s/restic-backup" $clusterName) }}
{{- $externalValues := deepCopy .Values }}
{{- $_ := set $externalValues "SubPathSecrets" (list $subPathSecret) }}
{{- include "external-secret-manager.subpath" (dict "Values" $externalValues "Release" .Release "Chart" .Chart "Capabilities" .Capabilities) -}}

{{- end }}