{{- if .Values.resticBackup.enabled }}
{{- $restic := .Values.resticBackup }}
{{- $cachePVCName := required "resticBackup.cachePVC.name is required when resticBackup.enabled" $restic.cachePVC.name }}
{{- $configMapName := default "restic-backup" $restic.configMapName }}
{{- $secretName := default $configMapName $restic.secretName }}
{{- $hostname := default .Release.Namespace $restic.hostname }}
{{- $retryLock := default "15m" $restic.retryLock }}
{{- $jobDefaults := dict "cachePVCName" $cachePVCName "envSecretName" $secretName "configMapName" $configMapName }}
{{- $newline := "\n" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configMapName }}
  namespace: {{ .Release.Namespace }}
data:
  RETRY_LOCK: {{ $retryLock | quote }}
  HOSTNAME: {{ $hostname | quote }}

{{- $pruneJob := default (dict) $restic.pruneJob }}
{{- $pruneEnabled := or (not (hasKey $pruneJob "enabled")) $pruneJob.enabled }}
{{- if $pruneEnabled }}
  {{- $job := merge (deepCopy $jobDefaults) $pruneJob }}
  {{- if not (hasKey $job "name") }}{{- $_ := set $job "name" "restic-prune" }}{{- end }}
  {{- if not (hasKey $job "schedule") }}{{- $_ := set $job "schedule" "@weekly" }}{{- end }}
  {{- if not (hasKey $job "script") }}{{- $_ := set $job "script" (printf "echo \"[restic prune] Starting prune operation\"%srestic prune" $newline) }}{{- end }}
  {{- include "library-app-chart.restic.cronJob" (dict "root" . "job" $job) }}
{{- end }}

{{- $checkJob := default (dict) $restic.checkJob }}
{{- $checkEnabled := or (not (hasKey $checkJob "enabled")) $checkJob.enabled }}
{{- if $checkEnabled }}
  {{- $job := merge (deepCopy $jobDefaults) $checkJob }}
  {{- if not (hasKey $job "name") }}{{- $_ := set $job "name" "restic-check" }}{{- end }}
  {{- if not (hasKey $job "schedule") }}{{- $_ := set $job "schedule" "@monthly" }}{{- end }}
  {{- if not (hasKey $job "script") }}{{- $_ := set $job "script" (printf "echo \"[restic check] Starting check operation\"%srestic check" $newline) }}{{- end }}
  {{- include "library-app-chart.restic.cronJob" (dict "root" . "job" $job) }}
{{- end }}

{{- /* Expose only the External Secrets inputs we need for restic backups */}}
{{- $clusterName := default .Release.Namespace .Values.clusterName }}
{{- $subPathSecret := dict "name" $secretName "remoteRefKey" (printf "/k8s-%s/restic-backup" $clusterName) }}
{{- $externalValues := deepCopy .Values }}
{{- $_ := set $externalValues "SubPathSecrets" (list $subPathSecret) }}
{{- include "external-secret-manager.subpath" (dict "Values" $externalValues "Release" .Release "Chart" .Chart "Capabilities" .Capabilities) -}}

{{- end }}
