{{- $backupTracker := dict "enabled" false }}
{{- range $pvcName, $pvc := .Values.persistentVolumeClaims }}
{{- if and $pvc.backup $pvc.backup.enabled }}
{{- $_ := set $backupTracker "enabled" true }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: restic-backup-{{ $pvcName }}
  namespace: {{ $.Release.Namespace }}
data:
  RETRY_LOCK: "15m"
  HOSTNAME: "{{ $.Release.Namespace }}-{{ $pvcName }}"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: restic-backup-{{ $pvcName }}
  namespace: {{ $.Release.Namespace }}
spec:
  schedule: "@hourly"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 172800 # 2 days
      backoffLimit: 4
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: restic
              image: restic/restic:latest
              envFrom:
                - secretRef:
                    name: restic-backup
                  prefix: "RESTIC_"
                - configMapRef:
                    name: restic-backup-{{ $pvcName }}
                  prefix: "RESTIC_"
              volumeMounts:
                - name: data
                  mountPath: /data
              command:
                - /bin/sh
                - -c
                - |
                  set -euo pipefail

                  export B2_ACCOUNT_ID=${RESTIC_b2_account_id}
                  export B2_ACCOUNT_KEY=${RESTIC_b2_account_key}
                  export RESTIC_PASSWORD=${RESTIC_password}
                  export RESTIC_REPOSITORY=${RESTIC_repository}

                  echo "[backup] Checking/initializing restic repo..."
                  if ! restic snapshots > /dev/null 2>&1; then
                    echo "[backup] Repo not found, initializing..."
                    restic init
                  fi

                  echo "[backup] Running backup of /data ..."
                  restic backup /data \
                    --skip-if-unchanged \
                    --retry-lock "$RESTIC_RETRY_LOCK" \
                    --host "$RESTIC_HOSTNAME" \
                    --tag="pvc={{ $pvcName }}" \
                    --tag="namespace={{ $.Release.Namespace }}"

                  echo "[backup] Applying retention policy + prune..."
                  restic forget \
                    --keep-daily 7 \
                    --keep-weekly 4 \
                    --keep-monthly 3 \
                    --retry-lock "$RESTIC_RETRY_LOCK" \
                    --prune \
                    --tag="pvc={{ $pvcName }}" \
                    --tag="namespace={{ $.Release.Namespace }}"

                  echo "[backup] Done."

          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: {{ $pvcName }}

{{- end }}
{{- end }}

{{- if $backupTracker.enabled }}
{{- /* Expose only the External Secrets inputs we need for restic backups */}}
{{- $clusterName := default $.Release.Namespace $.Values.clusterName }}
{{- $subPathSecret := dict "name" "restic-backup" "remoteRefKey" (printf "/k8s-%s/restic-backup" $clusterName) }}
{{- $externalValues := deepCopy .Values }}
{{- $_ := set $externalValues "SubPathSecrets" (list $subPathSecret) }}
{{- include "external-secret-manager.subpath" (dict "Values" $externalValues "Release" .Release "Chart" .Chart "Capabilities" .Capabilities) -}}
{{- end }}